In [1]:
import os
from pathlib import Path

import geomulticorr as gmc

import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings(
    "ignore",
    category=UserWarning,
    module="geoutils"
    )

geomulticorr 0.1.0

In [2]:
session = gmc.open_gmc_session(
    "/home/cusicand/03_Data/GMC_projects/GMC_VieuxMarinet/",
    epsg_code=9793
)

[GMC ✓] : New GMC project: 'GMC_VieuxMarinet'
[GMC ✓] : Creating new GMC structure in: /home/cusicand/03_Data/GMC_projects/GMC_VieuxMarinet
[GMC »] : Default GMC-geodatabase template copied into /home/cusicand/03_Data/GMC_projects/GMC_VieuxMarinet
[GMC »] : Making a copy of 'GMC-QGIS-Mapset' template into /home/cusicand/03_Data/GMC_projects/GMC_VieuxMarinet
[GMC ✓] : Setting GMC folder structure
[GMC »] : Creating 'raster_data_GMC_VieuxMarinet' folder
[GMC ▸] : Session 'GMC_VieuxMarinet' initialized.

In [3]:
raster_bank = session.map_georasters_bank(
    "/media/cusicand/LaCie/VieuxMarinet/croped_tiles/")

Output()

In [4]:
raster_bank

,filename,sensor,xRes,yRes,bands,rows,cols,acq_date,file_path,sensor_family,sensor_platform,acq_datetime,src_crs,geometry
0,19900905_aerial_VieuxMarinet_1.0m_ortho_corrOK...,aerial,1.0,1.0,1,2100,1900,1990-09-05,/media/cusicand/LaCie/VieuxMarinet/croped_tile...,aerial,aerial,1990-09-05,EPSG:9793,"POLYGON ((1007315 6392710, 1007315 6392710.42,..."
1,20240704_aerial_VieuxMarinet_1.0m_ortho_corrOK...,aerial,1.0,1.0,1,2100,1900,2024-07-04,/media/cusicand/LaCie/VieuxMarinet/croped_tile...,aerial,aerial,2024-07-04,EPSG:9793,"POLYGON ((1007315 6392710, 1007315 6392710.42,..."
2,19490820_aerial_VieuxMarinet_1.0m_ortho_corrOK...,aerial,1.0,1.0,1,2100,1900,1949-08-20,/media/cusicand/LaCie/VieuxMarinet/croped_tile...,aerial,aerial,1949-08-20,EPSG:9793,"POLYGON ((1007315 6392710, 1007315 6392710.42,..."
3,19560701_aerial_VieuxMarinet_1.0m_ortho_corrOK...,aerial,1.0,1.0,1,2100,1900,1956-07-01,/media/cusicand/LaCie/VieuxMarinet/croped_tile...,aerial,aerial,1956-07-01,EPSG:9793,"POLYGON ((1007315 6392710, 1007315 6392710.42,..."
4,20040722_aerial_VieuxMarinet_1.0m_ortho_corrOK...,aerial,1.0,1.0,1,2100,1900,2004-07-22,/media/cusicand/LaCie/VieuxMarinet/croped_tile...,aerial,aerial,2004-07-22,EPSG:9793,"POLYGON ((1007315 6392710, 1007315 6392710.42,..."
5,19790716_aerial_VieuxMarinet_1.0m_ortho_corrOK...,aerial,1.0,1.0,1,2100,1900,1979-07-16,/media/cusicand/LaCie/VieuxMarinet/croped_tile...,aerial,aerial,1979-07-16,EPSG:9793,"POLYGON ((1007315 6392710, 1007315 6392710.42,..."
6,20130810_aerial_VieuxMarinet_1.0m_ortho_corrOK...,aerial,1.0,1.0,1,2100,1900,2013-08-10,/media/cusicand/LaCie/VieuxMarinet/croped_tile...,aerial,aerial,2013-08-10,EPSG:9793,"POLYGON ((1007315 6392710, 1007315 6392710.42,..."

In [5]:
# also works with: a .tif (footprint), a gu.Vector, or a gu.Raster; dissolve=True to merge features
session.insert_pzone_from_file(
    "/media/cusicand/LaCie/VieuxMarinet/croped_tiles/AOI_VieuxMarinet.gpkg",
    pz_name="VieuxMarinet",
    pz_shortname="VM")

[GMC ✓] : Pzone 'VieuxMarinet' inserted.
[GMC ✓] : Pzone 'VieuxMarinet' (VM) stored in geodatabase from '/media/cusicand/LaCie/VieuxMarinet/croped_tiles/AOI_VieuxMarinet.gpkg'.

In [6]:
session.get_pzones_overview()

,pz_name,pz_shortname,pz_surf,geometry
0,VieuxMarinet,VM,None,"POLYGON ((1007315 6394810, 1007315 6392710, 10..."

In [ ]:
session.sieve_bulk(raster_bank,
                   target_resolution=1,
                   out_dtype="Float32",
                   )

[GMC ℹ] : Map epsg : EPSG:9793
[GMC ℹ] : Target resolution: 1 (EPSG:9793)
[GMC ℹ] : Pzone: VieuxMarinet
[GMC ℹ] : Intersecting rasters: 7

Output()

                  sieve_bulk — processed thumbs
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━━┳━━━━━━━━┓
┃ Thumb                              ┃ Sensor ┃ Res (m) ┃ Status ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━━━╇━━━━━━━━┩
│ VieuxMarinet_1949-08-20_aerial.tif │ aerial │       1 │ ✓ done │
│ VieuxMarinet_1956-07-01_aerial.tif │ aerial │       1 │ ✓ done │
│ VieuxMarinet_1979-07-16_aerial.tif │ aerial │       1 │ ✓ done │
│ VieuxMarinet_1990-09-05_aerial.tif │ aerial │       1 │ ✓ done │
│ VieuxMarinet_2004-07-22_aerial.tif │ aerial │       1 │ ✓ done │
│ VieuxMarinet_2013-08-10_aerial.tif │ aerial │       1 │ ✓ done │
│ VieuxMarinet_2024-07-04_aerial.tif │ aerial │       1 │ ✓ done │
└────────────────────────────────────┴────────┴─────────┴────────┘

{'VieuxMarinet': [PosixPath('/home/cusicand/03_Data/GMC_projects/GMC_VieuxMarinet/raster_data_GMC_VieuxMarinet/VieuxMarinet/opticals/VieuxMarinet_1949-08-20_aerial.tif'),
  PosixPath('/home/cusicand/03_Data/GMC_projects/GMC_VieuxMarinet/raster_data_GMC_VieuxMarinet/VieuxMarinet/opticals/VieuxMarinet_1956-07-01_aerial.tif'),
  PosixPath('/home/cusicand/03_Data/GMC_projects/GMC_VieuxMarinet/raster_data_GMC_VieuxMarinet/VieuxMarinet/opticals/VieuxMarinet_1979-07-16_aerial.tif'),
  PosixPath('/home/cusicand/03_Data/GMC_projects/GMC_VieuxMarinet/raster_data_GMC_VieuxMarinet/VieuxMarinet/opticals/VieuxMarinet_1990-09-05_aerial.tif'),
  PosixPath('/home/cusicand/03_Data/GMC_projects/GMC_VieuxMarinet/raster_data_GMC_VieuxMarinet/VieuxMarinet/opticals/VieuxMarinet_2004-07-22_aerial.tif'),
  PosixPath('/home/cusicand/03_Data/GMC_projects/GMC_VieuxMarinet/raster_data_GMC_VieuxMarinet/VieuxMarinet/opticals/VieuxMarinet_2013-08-10_aerial.tif'),
  PosixPath('/home/cusicand/03_Data/GMC_projects/GMC_VieuxMarinet/raster_data_GMC_VieuxMarinet/VieuxMarinet/opticals/VieuxMarinet_2024-07-04_aerial.tif')]}